package org.scau.mall.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.scau.mall.service.pojo.PmsMenu;
import org.scau.mall.service.pojo.PmsMenuExample;

public interface PmsMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_menu
     *
     * @mbggenerated
     */
    int countByExample(PmsMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_menu
     *
     * @mbggenerated
     */
    int deleteByExample(PmsMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_menu
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_menu
     *
     * @mbggenerated
     */
    int insert(PmsMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_menu
     *
     * @mbggenerated
     */
    int insertSelective(PmsMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_menu
     *
     * @mbggenerated
     */
    List<PmsMenu> selectByExample(PmsMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_menu
     *
     * @mbggenerated
     */
    PmsMenu selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_menu
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") PmsMenu record, @Param("example") PmsMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_menu
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") PmsMenu record, @Param("example") PmsMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_menu
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PmsMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_menu
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PmsMenu record);
}