package org.scau.mall.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.scau.mall.service.pojo.PmsOrders;
import org.scau.mall.service.pojo.PmsOrdersExample;

public interface PmsOrdersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_orders
     *
     * @mbggenerated
     */
    int countByExample(PmsOrdersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_orders
     *
     * @mbggenerated
     */
    int deleteByExample(PmsOrdersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_orders
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String orderNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_orders
     *
     * @mbggenerated
     */
    int insert(PmsOrders record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_orders
     *
     * @mbggenerated
     */
    int insertSelective(PmsOrders record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_orders
     *
     * @mbggenerated
     */
    List<PmsOrders> selectByExample(PmsOrdersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_orders
     *
     * @mbggenerated
     */
    PmsOrders selectByPrimaryKey(String orderNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_orders
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") PmsOrders record, @Param("example") PmsOrdersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_orders
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") PmsOrders record, @Param("example") PmsOrdersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_orders
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PmsOrders record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_orders
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PmsOrders record);
}