package org.scau.mall.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.scau.mall.service.pojo.PmsUser;
import org.scau.mall.service.pojo.PmsUserExample;

public interface PmsUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_user
     *
     * @mbggenerated
     */
    int countByExample(PmsUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_user
     *
     * @mbggenerated
     */
    int deleteByExample(PmsUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_user
     *
     * @mbggenerated
     */
    int insert(PmsUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_user
     *
     * @mbggenerated
     */
    int insertSelective(PmsUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_user
     *
     * @mbggenerated
     */
    List<PmsUser> selectByExample(PmsUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_user
     *
     * @mbggenerated
     */
    PmsUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_user
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") PmsUser record, @Param("example") PmsUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_user
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") PmsUser record, @Param("example") PmsUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PmsUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PmsUser record);
}