package org.scau.mall.pojo;

import java.io.Serializable;
import java.util.Date;
import java.math.BigDecimal;

public class PmsClientLoanRecord implements Serializable {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column pms_client_loan_record.id
     * @mbg.generated
     */
    private Integer id;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column pms_client_loan_record.type
     * @mbg.generated
     */
    private String type;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column pms_client_loan_record.amount
     * @mbg.generated
     */
    private BigDecimal amount;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column pms_client_loan_record.client_id
     * @mbg.generated
     */
    private Integer clientId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column pms_client_loan_record.status
     * @mbg.generated
     */
    private Integer status;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column pms_client_loan_record.created_at
     * @mbg.generated
     */
    private Date createdAt;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column pms_client_loan_record.updated_at
     * @mbg.generated
     */
    private Date updatedAt;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table pms_client_loan_record
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column pms_client_loan_record.id
     * @return  the value of pms_client_loan_record.id
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column pms_client_loan_record.id
     * @param id  the value for pms_client_loan_record.id
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column pms_client_loan_record.type
     * @return  the value of pms_client_loan_record.type
     * @mbg.generated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column pms_client_loan_record.type
     * @param type  the value for pms_client_loan_record.type
     * @mbg.generated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column pms_client_loan_record.amount
     * @return  the value of pms_client_loan_record.amount
     * @mbg.generated
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column pms_client_loan_record.amount
     * @param amount  the value for pms_client_loan_record.amount
     * @mbg.generated
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column pms_client_loan_record.client_id
     * @return  the value of pms_client_loan_record.client_id
     * @mbg.generated
     */
    public Integer getClientId() {
        return clientId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column pms_client_loan_record.client_id
     * @param clientId  the value for pms_client_loan_record.client_id
     * @mbg.generated
     */
    public void setClientId(Integer clientId) {
        this.clientId = clientId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column pms_client_loan_record.status
     * @return  the value of pms_client_loan_record.status
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column pms_client_loan_record.status
     * @param status  the value for pms_client_loan_record.status
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column pms_client_loan_record.created_at
     * @return  the value of pms_client_loan_record.created_at
     * @mbg.generated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column pms_client_loan_record.created_at
     * @param createdAt  the value for pms_client_loan_record.created_at
     * @mbg.generated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column pms_client_loan_record.updated_at
     * @return  the value of pms_client_loan_record.updated_at
     * @mbg.generated
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column pms_client_loan_record.updated_at
     * @param updatedAt  the value for pms_client_loan_record.updated_at
     * @mbg.generated
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table pms_client_loan_record
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        PmsClientLoanRecord other = (PmsClientLoanRecord) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
                && (this.getType() == null ? other.getType() == null : this.getType().equals(other.getType()))
                && (this.getAmount() == null ? other.getAmount() == null : this.getAmount().equals(other.getAmount()))
                && (this.getClientId() == null ? other.getClientId() == null : this.getClientId().equals(other.getClientId()))
                && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
                && (this.getCreatedAt() == null ? other.getCreatedAt() == null : this.getCreatedAt().equals(other.getCreatedAt()))
                && (this.getUpdatedAt() == null ? other.getUpdatedAt() == null : this.getUpdatedAt().equals(other.getUpdatedAt()));
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table pms_client_loan_record
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getType() == null) ? 0 : getType().hashCode());
        result = prime * result + ((getAmount() == null) ? 0 : getAmount().hashCode());
        result = prime * result + ((getClientId() == null) ? 0 : getClientId().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getCreatedAt() == null) ? 0 : getCreatedAt().hashCode());
        result = prime * result + ((getUpdatedAt() == null) ? 0 : getUpdatedAt().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table pms_client_loan_record
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", type=").append(type);
        sb.append(", amount=").append(amount);
        sb.append(", clientId=").append(clientId);
        sb.append(", status=").append(status);
        sb.append(", createdAt=").append(createdAt);
        sb.append(", updatedAt=").append(updatedAt);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}